### ISSUE TITLE
FakkuDroid v2.6.0 breaks the download option in Home

### ISSUE THREAD

**Issue by aalemayhu** [csaki/FakkuDroid#3]
When attempting to download new content from the Home view, I get the following toast message ''Error downloading: x". Where x is the title of the content.

**Comment by csaki** [comment]
Hey man, I'm sorry for the delay... Do you still have that problem?

**Comment by aalemayhu** [comment]
I tested the lastest version just today. I can confirm that v2.7.0 fixes this issue. Thank you.

PS: Maybe you should have a mailinglist for broadcasting new versions of the application, or even better let the application check for updates on a daily basis.

**Comment by csaki** [comment]
The application check for updates, but only notify to the user, not download. I'm going to close the issue. 
Thanks again for your feedback, and sorry for the delay.

Look for "CheckerVersion"
https://github.com/csaki/FakkuDroid/blob/master/src/com/fakkudroid/MainActivity.java
